import {useState} from 'react';
import {useSearchParams} from 'react-router';
import {CheckCircle2,PackageCheck,XCircle,Search} from 'lucide-react';
import {PageHeader} from '../../components/ui/PageHeader';
import {DataTable,type Column} from '../../components/ui/DataTable';
import {StatusBadge} from '../../components/ui/StatusBadge';
import {Modal} from '../../components/ui/Modal';
import {Field,Select,Textarea} from '../../components/forms/FormField';
import {useReturnsQuery,useApproveReturnMutation,useRejectReturnMutation,useReceiveReturnMutation,useTransitionReturnMutation} from '../../services/returnApi';
import {useWarehousesQuery} from '../../services/inventoryApi';
import {rowsOf,countOf,apiError} from '../../utils/data';
import {Pagination} from '../../components/ui/Pagination';
import {LoadingRows} from '../../components/ui/Loading';
import {ErrorState} from '../../components/ui/ErrorState';
import {useDebouncedValue} from '../../hooks/useDebouncedValue';
import {date,titleCase} from '../../utils/format';
import {useAppDispatch} from '../../store/hooks';
import {toast} from '../../features/ui/uiSlice';

export default function ReturnsPage(){
 const [searchParams]=useSearchParams(); const dispatch=useAppDispatch(),[page,setPage]=useState(1),[search,setSearch]=useState(searchParams.get('search')||''),[status,setStatus]=useState(searchParams.get('status')||''),[selected,setSelected]=useState<any>(null),[warehouse,setWarehouse]=useState(''),[notes,setNotes]=useState('');
 const debounced=useDebouncedValue(search,300);
 const q=useReturnsQuery({page,page_size:50,search:debounced||undefined,status:status||undefined}),wq=useWarehousesQuery({page_size:500});
 const [approve]=useApproveReturnMutation(),[reject]=useRejectReturnMutation(),[receive]=useReceiveReturnMutation(),[transition]=useTransitionReturnMutation();
 const act=async(fn:()=>Promise<any>,message:string)=>{try{await fn();dispatch(toast({type:'success',message}));setSelected(null);setNotes('')}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}};
 const nextFor=(s:string)=>s==='requested'?'review':s==='received'?'inspected':s==='inspected'?'refund_processing':s==='refund_processing'?'completed':'';
 const cols:Column<any>[]=[{key:'id',header:'Return',render:r=><button className="text-left" onClick={()=>setSelected(r)}><b>Return #{r.id}</b><div className="text-xs text-zinc-400">Order #{r.order}</div></button>},{key:'customer',header:'Customer',render:r=>`User #${r.user}`},{key:'items',header:'Items',render:r=><div><b>{r.items?.length||0} line(s)</b><div className="text-xs text-zinc-400">{(r.items||[]).reduce((a:number,x:any)=>a+Number(x.quantity||0),0)} unit(s)</div></div>},{key:'reason',header:'Reason',render:r=><span className="line-clamp-2 max-w-xs">{r.reason}</span>},{key:'status',header:'Status',render:r=><StatusBadge value={r.status}/>},{key:'date',header:'Requested',render:r=>date(r.created_at,true)},{key:'action',header:'',render:r=><button className="btn-secondary py-2" onClick={()=>setSelected(r)}>Review</button>}];
 const renderActions=()=>{if(!selected)return null;const n=nextFor(selected.status);if(['requested','review'].includes(selected.status))return <div className="grid gap-2 sm:grid-cols-3">{selected.status==='requested'&&<button className="btn-secondary" onClick={()=>act(()=>transition({id:selected.id,status:'review',notes}).unwrap(),'Moved to review.')}>Start Review</button>}<button className="btn-primary" onClick={()=>act(()=>approve(selected.id).unwrap(),'Return approved.')}><CheckCircle2 size={16}/>Approve</button><button className="btn-danger" onClick={()=>act(()=>reject({id:selected.id,notes}).unwrap(),'Return rejected.')}><XCircle size={16}/>Reject</button></div>;if(selected.status==='approved')return <div className="flex gap-2"><Select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="">Receiving warehouse…</option>{rowsOf<any>(wq.data).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select><button disabled={!warehouse} className="btn-primary whitespace-nowrap" onClick={()=>act(()=>receive({id:selected.id,warehouse:Number(warehouse)}).unwrap(),'Return stock received.')}><PackageCheck size={16}/>Receive</button></div>;if(n)return <button className="btn-primary w-full" onClick={()=>act(()=>transition({id:selected.id,status:n,notes}).unwrap(),`Return moved to ${titleCase(n)}.`)}>Mark {titleCase(n)}</button>;return null};
 return <><PageHeader title="Returns" description="Search, review, approve, receive and inspect customer return requests with backend-controlled stock handling."/><div className="mb-4 grid gap-2 md:grid-cols-2"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input className="input pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Order, customer, phone, reason…"/></label><select className="input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['requested','review','approved','rejected','received','inspected','refund_processing','completed'].map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select></div>{q.isLoading?<LoadingRows/>:q.isError?<ErrorState onRetry={()=>q.refetch()}/>:<><DataTable rows={rowsOf<any>(q.data)} columns={cols} getKey={r=>r.id}/><Pagination count={countOf(q.data)} page={page} onPage={setPage}/></>}<Modal open={!!selected} onClose={()=>setSelected(null)} title={`Return #${selected?.id||''}`}><div className="space-y-5"><div className="flex justify-between"><div><div className="text-sm text-zinc-500">Order #{selected?.order}</div><div className="font-semibold">Customer #{selected?.user}</div></div><StatusBadge value={selected?.status||''}/></div><div className="rounded-xl bg-zinc-50 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-zinc-400">Reason</div><p className="mt-2 text-sm leading-6 text-zinc-700">{selected?.reason}</p></div><div><div className="mb-2 text-sm font-semibold">Return items</div><div className="space-y-2">{selected?.items?.map((x:any)=><div key={x.id} className="flex justify-between rounded-xl border border-zinc-200 p-3 text-sm"><span>Order item #{x.order_item}</span><span>{x.quantity} unit(s) · {x.restock?'Restock':'No restock'}</span></div>)}</div></div><Field label="Internal notes"><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Inspection or rejection notes…"/></Field>{renderActions()}</div></Modal></>;
}
