import {useEffect,useMemo,useState} from 'react'
import {useNavigate,useParams} from 'react-router'
import {ArrowLeft,ArrowRight,Boxes,Check,ChevronLeft,ChevronRight,Image as ImageIcon,Layers3,Package,SearchCheck,Sparkles,Star,Trash2} from 'lucide-react'
import {PageHeader} from '../../components/ui/PageHeader'
import {Field,Input,Select,Textarea,Switch} from '../../components/forms/FormField'
import {RichTextEditor} from '../../components/ui/RichTextEditor'
import {ImageUploadPicker} from '../../components/ui/ImageUploadPicker'
import {PageLoading} from '../../components/ui/Loading'
import {ErrorState} from '../../components/ui/ErrorState'
import {useAppDispatch} from '../../store/hooks'
import {toast} from '../../features/ui/uiSlice'
import {apiError,rowsOf} from '../../utils/data'
import {
  useAttributeValuesQuery,useAttributesQuery,useBeautyProfilesQuery,useBrandsQuery,useCategoriesQuery,useClaimsQuery,
  useConcernsQuery,useCreateBeautyProfileMutation,useCreateProductClaimMutation,useCreateProductMutation,useCreateVariantMutation,
  useHairTypesQuery,useIngredientsQuery,useProductClaimsQuery,useProductQuery,usePublishProductMutation,useSkinTypesQuery,
  useUpdateBeautyProfileMutation,useUpdateProductMutation,useUploadImagesMutation,useVariantsQuery,useImagesQuery,useDeleteImageMutation,useSetPrimaryMutation,useReorderImagesMutation,
} from '../../services/catalogApi'
import {useAdjustStockMutation,useResolveStockItemMutation,useUpdateThresholdsMutation,useWarehousesQuery} from '../../services/inventoryApi'
import type {Attribute,AttributeValue} from '../../types'
import {mediaUrl} from '../../utils/media'

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const steps=[['Basic Information',Package],['Product Type & Pricing',Layers3],['Attributes / Variants',Layers3],['Images',ImageIcon],['Beauty Information',Sparkles],['Inventory',Boxes],['Publish',SearchCheck]] as const
const combinations=(groups:number[][])=>groups.reduce<number[][]>((acc,g)=>acc.flatMap(a=>g.map(v=>[...a,v])),[[]])
const emptyForm={
  name:'',slug:'',product_type:'simple',sku:'',barcode:'',brand:'',category:'',base_price:'0',compare_at_price:'',cost_price:'',weight:'',tax_class:'standard',status:'draft',
  short_description:'',description:'',featured:false,new_arrival:false,bestseller:false,trending:false,
  beauty:{benefits:'',ingredients_text:'',how_to_use:'',precautions:'',country_of_origin:'',shelf_life:'',pao:'',skin_types:[] as number[],hair_types:[] as number[],concerns:[] as number[],ingredients:[] as number[]},
  warehouse:'',simple_stock:'0',low_stock_threshold:'5',seo_title:'',seo_description:'',beautyProfileId:undefined as number|undefined,
}

type VariantDraft={values:number[];sku:string;price_override:string;cost_price:string;weight:string;stock:string}

export default function ProductWizardPage(){
  const {id}=useParams(); const editId=id?Number(id):undefined; const nav=useNavigate(); const dispatch=useAppDispatch()
  const existing=useProductQuery(editId!,{skip:!editId})
  const brands=useBrandsQuery({page_size:100}); const categories=useCategoriesQuery({page_size:100}); const attrs=useAttributesQuery({page_size:100}); const values=useAttributeValuesQuery({page_size:100})
  const skins=useSkinTypesQuery({page_size:100}); const hairs=useHairTypesQuery({page_size:100}); const concerns=useConcernsQuery({page_size:100}); const ingredients=useIngredientsQuery({page_size:100}); const claims=useClaimsQuery({page_size:100}); const warehouses=useWarehousesQuery({page_size:100})
  const [createProduct]=useCreateProductMutation(); const [updateProduct]=useUpdateProductMutation(); const [createVariant]=useCreateVariantMutation(); const [uploadImages]=useUploadImagesMutation(); const [deleteImage]=useDeleteImageMutation(); const [setPrimaryImage]=useSetPrimaryMutation(); const [reorderImages]=useReorderImagesMutation()
  const [createProfile]=useCreateBeautyProfileMutation(); const [updateProfile]=useUpdateBeautyProfileMutation(); const [createProductClaim]=useCreateProductClaimMutation(); const [publish]=usePublishProductMutation()
  const [resolveStock]=useResolveStockItemMutation(); const [adjustStock]=useAdjustStockMutation(); const [updateThresholds]=useUpdateThresholdsMutation()
  const [step,setStep]=useState(0); const [productId,setProductId]=useState<number|undefined>(editId); const [busy,setBusy]=useState(false); const [files,setFiles]=useState<File[]>([]); const [primaryImageIndex,setPrimaryImageIndex]=useState(0)
  const [form,setForm]=useState<any>(emptyForm); const [errors,setErrors]=useState<Record<string,string>>({}); const [selectedAttrs,setSelectedAttrs]=useState<Record<number,number[]>>({})
  const [variantRows,setVariantRows]=useState<VariantDraft[]>([]); const [createdVariants,setCreatedVariants]=useState<any[]>([]); const [selectedClaims,setSelectedClaims]=useState<number[]>([])
  const variantQuery=useVariantsQuery({product:editId},{skip:!editId}); const profiles=useBeautyProfilesQuery({product:editId},{skip:!editId}); const productClaims=useProductClaimsQuery({product:editId},{skip:!editId}); const existingImagesQuery=useImagesQuery(productId?{product:productId,page_size:200}:undefined,{skip:!productId})

  useEffect(()=>{if(!existing.data)return;const p:any=existing.data;setProductId(p.id);setForm((f:any)=>({...f,...p,brand:typeof p.brand==='object'?p.brand.id:p.brand,category:typeof p.category==='object'?p.category.id:p.category,sku:p.sku||'',barcode:p.barcode||'',compare_at_price:p.compare_at_price||'',cost_price:p.cost_price||'',weight:p.weight||'',status:p.status||'draft'}))},[existing.data])
  useEffect(()=>{const profile=rowsOf<any>(profiles.data)[0];if(profile)setForm((f:any)=>({...f,beauty:{...f.beauty,...profile},beautyProfileId:profile.id}))},[profiles.data])
  useEffect(()=>{const pcs=rowsOf<any>(productClaims.data);if(pcs.length)setSelectedClaims(pcs.filter((x:any)=>x.active).map((x:any)=>Number(x.claim)))},[productClaims.data])

  const attributeList=rowsOf<Attribute>(attrs.data), valueList=rowsOf<AttributeValue>(values.data)
  const generated=useMemo(()=>{const groups=Object.values(selectedAttrs).filter(v=>v.length);return groups.length?combinations(groups):[]},[selectedAttrs])
  useEffect(()=>{setVariantRows(prev=>generated.map(vals=>{const previous=prev.find(x=>x.values.join(',')===vals.join(','));if(previous)return previous;const labels=vals.map(v=>valueList.find(x=>x.id===v)?.value||v).join('-');return {values:vals,sku:`${slugify(form.name||'PRODUCT').toUpperCase()}-${slugify(labels).toUpperCase()}`,price_override:'',cost_price:'',weight:'',stock:'0'}}))},[JSON.stringify(generated),valueList.length,form.name])

  const brandRows=rowsOf<any>(brands.data),categoryRows=rowsOf<any>(categories.data),skinRows=rowsOf<any>(skins.data),hairRows=rowsOf<any>(hairs.data),concernRows=rowsOf<any>(concerns.data),ingredientRows=rowsOf<any>(ingredients.data),claimRows=rowsOf<any>(claims.data),warehouseRows=rowsOf<any>(warehouses.data)
  const existingImages=rowsOf<any>(existingImagesQuery.data).filter((x:any)=>!x.variant).sort((a:any,b:any)=>Number(a.order||0)-Number(b.order||0))
  const toggleBeauty=(key:string,value:number)=>setForm((f:any)=>{const current=f.beauty[key]||[];return {...f,beauty:{...f.beauty,[key]:current.includes(value)?current.filter((x:number)=>x!==value):[...current,value]}}})

  const validate=(target:number)=>{const e:Record<string,string>={};if(target===0){if(!form.name.trim())e.name='Product name is required.';if(!form.brand)e.brand='Brand is required.';if(!form.category)e.category='Category is required.'}if(target===1){if(form.product_type==='simple'&&!form.sku.trim())e.sku='SKU is required for simple products.';if(Number(form.base_price)<0)e.base_price='Price cannot be negative.'}if(target===2&&form.product_type==='variable'){if(!variantRows.length)e.variants='Select attribute values to generate at least one variant.';if(variantRows.some(r=>!r.sku.trim()))e.variants='Every variant needs a SKU.'}setErrors(e);return Object.keys(e).length===0}

  const saveBase=async()=>{const body:any={name:form.name.trim(),slug:form.slug.trim()||slugify(form.name),product_type:form.product_type,sku:form.product_type==='simple'?form.sku.trim():null,barcode:form.barcode.trim()||null,brand:Number(form.brand),category:Number(form.category),base_price:String(form.base_price||'0'),compare_at_price:form.compare_at_price||null,cost_price:form.cost_price||null,status:form.status||'draft',short_description:form.short_description||'',description:form.description||'',weight:form.weight||null,tax_class:form.tax_class||'',featured:!!form.featured,new_arrival:!!form.new_arrival,bestseller:!!form.bestseller,trending:!!form.trending};const p:any=productId?await updateProduct({id:productId,body}).unwrap():await createProduct(body).unwrap();setProductId(p.id);return Number(p.id)}
  const saveVariants=async(pid:number)=>{if(form.product_type!=='variable')return;const existingRows=rowsOf<any>(variantQuery.data);const made:any[]=[];for(const r of variantRows){const found=existingRows.find((v:any)=>v.sku===r.sku);if(found){made.push(found);continue}made.push(await createVariant({product:pid,sku:r.sku,price_override:r.price_override||null,cost_price:r.cost_price||null,weight:r.weight||null,is_active:true,attribute_value_ids:r.values} as any).unwrap())}setCreatedVariants(made)}
  const saveImages=async(pid:number)=>{if(!files.length)return;const body=new FormData();body.append('product',String(pid));body.append('primary_index',String(primaryImageIndex));files.forEach(f=>body.append('images',f));await uploadImages(body).unwrap();setFiles([]);setPrimaryImageIndex(0)}
  const setExistingFeature=async(imageId:number)=>{try{await setPrimaryImage(imageId).unwrap();dispatch(toast({type:'success',message:'Feature image updated.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
  const removeExistingImage=async(imageId:number)=>{if(!confirm('Delete this product image?'))return;try{await deleteImage(imageId).unwrap();dispatch(toast({type:'success',message:'Image deleted.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
  const moveExistingImage=async(index:number,dir:-1|1)=>{if(!productId)return;const target=index+dir;if(target<0||target>=existingImages.length)return;const ordered=[...existingImages];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];try{await reorderImages({product:productId,image_ids:ordered.map((x:any)=>x.id)}).unwrap();dispatch(toast({type:'success',message:'Image order updated.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
  const saveBeauty=async(pid:number)=>{const body={product:pid,...form.beauty,skin_types:(form.beauty.skin_types||[]).map(Number),hair_types:(form.beauty.hair_types||[]).map(Number),concerns:(form.beauty.concerns||[]).map(Number),ingredients:(form.beauty.ingredients||[]).map(Number)};if(form.beautyProfileId)await updateProfile({id:form.beautyProfileId,body}).unwrap();else{const result:any=await createProfile(body).unwrap();setForm((f:any)=>({...f,beautyProfileId:result?.id}))}const existingIds=rowsOf<any>(productClaims.data).map((x:any)=>Number(x.claim));for(const claim of selectedClaims.filter(x=>!existingIds.includes(x)))await createProductClaim({product:pid,claim,is_verified:false,active:true}).unwrap()}
  const saveStock=async(pid:number)=>{if(!form.warehouse)return;const warehouse=Number(form.warehouse);if(form.product_type==='simple'){const item:any=await resolveStock({product:pid}).unwrap();const stock:any=await adjustStock({stock_item:item.id,warehouse,mode:'set',new_quantity:Number(form.simple_stock||0),note:'Stock set from product editor'}).unwrap();await updateThresholds({id:stock.id,low_stock_threshold:Number(form.low_stock_threshold||0)}).unwrap();return}const all=[...rowsOf<any>(variantQuery.data),...createdVariants];for(const row of variantRows){const variant=all.find((x:any)=>x.sku===row.sku);if(!variant)continue;const item:any=await resolveStock({variant:variant.id}).unwrap();const stock:any=await adjustStock({stock_item:item.id,warehouse,mode:'set',new_quantity:Number(row.stock||0),note:'Variant stock set from product editor'}).unwrap();await updateThresholds({id:stock.id,low_stock_threshold:Number(form.low_stock_threshold||0)}).unwrap()}}

  const next=async()=>{if(!validate(step))return;if(step===0){setStep(1);return}setBusy(true);try{let pid=productId;if(step===1)pid=await saveBase();if(step===2&&pid)await saveVariants(pid);if(step===3&&pid)await saveImages(pid);if(step===4&&pid)await saveBeauty(pid);if(step===5&&pid)await saveStock(pid);setStep(s=>Math.min(s+1,steps.length-1));dispatch(toast({type:'success',message:editId?'Changes saved.':'Draft saved.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}finally{setBusy(false)}}
  const saveAndExit=async()=>{if(!validate(0)||!validate(1))return;setBusy(true);try{await saveBase();dispatch(toast({type:'success',message:'Product saved.'}));nav('/catalog/products')}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}finally{setBusy(false)}}
  const doPublish=async()=>{if(!validate(0)||!validate(1)||(form.product_type==='variable'&&!productId&&!validate(2)))return;setBusy(true);try{const pid=await saveBase();if(form.product_type==='variable'&&variantRows.length)await saveVariants(pid);await publish(pid).unwrap();dispatch(toast({type:'success',message:'Product published.'}));nav('/catalog/products')}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}finally{setBusy(false)}}

  if(editId&&existing.isLoading)return <PageLoading/>
  if(editId&&existing.isError)return <ErrorState onRetry={existing.refetch}/>

  return <>
    <PageHeader title={editId?'Edit Product':'Create Product'} description={editId?'Update catalog, pricing, content, variants and inventory.':'Simple products require a SKU; variable products use real variant SKUs.'} actions={editId?<button className="btn-secondary" disabled={busy} onClick={saveAndExit}>Save & Exit</button>:undefined}/>
    <div className="mb-6 overflow-x-auto"><div className="flex min-w-[820px] gap-2">{steps.map(([name,Icon],i)=><button key={name} type="button" onClick={()=>{if(i===0||productId||i===1)setStep(i)}} className={`flex flex-1 items-center gap-2 rounded-xl border px-3 py-3 text-left text-xs font-semibold ${i===step?'border-pink-200 bg-pink-50 text-pink-800':i<step?'border-emerald-100 bg-emerald-50 text-emerald-700':'border-zinc-200 bg-white text-zinc-500'}`}><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white ring-1 ring-inset ring-current/10">{i<step?<Check size={13}/>:<Icon size={13}/>}</span>{name}</button>)}</div></div>
    <div className="panel p-5 sm:p-7">
      {step===0&&<div className="grid gap-5 lg:grid-cols-2">
        <Field label="Product name" error={errors.name}><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.slug||slugify(e.target.value)})}/></Field>
        <Field label="Slug"><Input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></Field>
        <Field label="Brand" error={errors.brand}><Select value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}><option value="">Select brand</option>{brandRows.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field>
        <Field label="Category" error={errors.category}><Select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select category</option>{categoryRows.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field>
        <div className="lg:col-span-2"><Field label="Short description"><Textarea value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})}/></Field></div>
        <div className="lg:col-span-2"><Field label="Description" hint="Rich text is stored as HTML and rendered by the storefront."><RichTextEditor value={form.description||''} onChange={description=>setForm((f:any)=>({...f,description}))}/></Field></div>
      </div>}
      {step===1&&<div className="space-y-6">
        <div className="grid gap-3 sm:grid-cols-2">{[['simple','Simple Product','Product owns SKU, pricing and stock identity.'],['variable','Variable Product','Real variants own SKU and stock identity.']].map(([value,title,description])=><button type="button" key={value} disabled={!!editId&&form.product_type!==value} onClick={()=>setForm({...form,product_type:value})} className={`rounded-2xl border p-5 text-left ${form.product_type===value?'border-pink-400 bg-pink-50':'border-zinc-200'}`}><b>{title}</b><p className="mt-1 text-sm text-zinc-500">{description}</p></button>)}</div>
        <div className="grid gap-5 lg:grid-cols-3">{form.product_type==='simple'&&<Field label="SKU" error={errors.sku}><Input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></Field>}<Field label="Barcode"><Input value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/></Field><Field label="Base price" error={errors.base_price}><Input type="number" min="0" step="0.01" value={form.base_price} onChange={e=>setForm({...form,base_price:e.target.value})}/></Field><Field label="Compare price"><Input type="number" min="0" step="0.01" value={form.compare_at_price} onChange={e=>setForm({...form,compare_at_price:e.target.value})}/></Field><Field label="Cost price"><Input type="number" min="0" step="0.01" value={form.cost_price} onChange={e=>setForm({...form,cost_price:e.target.value})}/></Field><Field label="Weight"><Input type="number" min="0" step="0.001" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></Field></div>
      </div>}
      {step===2&&(form.product_type==='simple'?<div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-6"><h3 className="font-semibold text-emerald-900">No variants required</h3><p className="mt-1 text-sm text-emerald-700">Continue directly to images. The product itself is the sellable stock identity.</p></div>:<div className="space-y-5">
        <div className="grid gap-4 lg:grid-cols-3">{attributeList.map(a=><div key={a.id} className="rounded-2xl border border-zinc-200 p-4"><b className="text-sm">{a.name}</b><div className="mt-3 flex flex-wrap gap-2">{valueList.filter(v=>Number(v.attribute)===a.id).map(v=>{const on=selectedAttrs[a.id]?.includes(v.id);return <button type="button" key={v.id} onClick={()=>setSelectedAttrs(s=>({...s,[a.id]:on?(s[a.id]||[]).filter(x=>x!==v.id):[...(s[a.id]||[]),v.id]}))} className={`rounded-lg border px-3 py-2 text-xs ${on?'border-pink-400 bg-pink-50 text-pink-800':'border-zinc-200'}`}>{v.swatch&&<span className="mr-1.5 inline-block h-2.5 w-2.5 rounded-full border" style={{background:v.swatch}}/>}{v.value}</button>})}</div></div>)}</div>
        {errors.variants&&<p className="text-sm text-red-600">{errors.variants}</p>}
        {variantRows.length?<div className="overflow-x-auto rounded-2xl border border-zinc-200"><table className="table"><thead><tr><th>Combination</th><th>SKU</th><th>Price override</th><th>Cost</th><th>Weight</th><th>Initial stock</th></tr></thead><tbody>{variantRows.map((r,i)=><tr key={r.values.join('-')}><td className="whitespace-nowrap font-medium">{r.values.map(v=>valueList.find(x=>x.id===v)?.value).join(' / ')}</td>{(['sku','price_override','cost_price','weight','stock'] as const).map(key=><td key={key}><input className="input min-w-28" value={r[key]} onChange={e=>setVariantRows(rows=>rows.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/></td>)}</tr>)}</tbody></table></div>:<div className="rounded-2xl border border-dashed border-zinc-300 p-8 text-center text-sm text-zinc-500">Select one or more values above to generate variants.</div>}
        {editId&&rowsOf<any>(variantQuery.data).length>0&&<div className="rounded-xl bg-zinc-50 p-4 text-sm text-zinc-600">Existing variants are preserved. Use <b>Catalog → Variants</b> to edit individual existing SKU records.</div>}
      </div>)}
      {step===3&&<div className="space-y-7">
        {productId&&<section>
          <div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="font-semibold">Current product gallery</h3><p className="mt-1 text-sm text-zinc-500">Saved images remain visible while editing. Set the Feature Image, reorder or delete them here.</p></div><span className="text-sm text-zinc-400">{existingImages.length} saved</span></div>
          {existingImagesQuery.isLoading?<div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[1,2,3,4].map(x=><div key={x} className="aspect-square animate-pulse rounded-2xl bg-zinc-100"/>)}</div>:existingImages.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{existingImages.map((x:any,i:number)=><article key={x.id} className={`overflow-hidden rounded-2xl border bg-white ${x.is_primary?'border-amber-400 ring-2 ring-amber-100':'border-zinc-200'}`}><div className="relative aspect-square bg-zinc-100"><img src={mediaUrl(x.image)} alt={x.alt_text||form.name} className="h-full w-full object-cover"/>{x.is_primary&&<span className="absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-amber-400 px-2.5 py-1 text-[11px] font-bold text-amber-950"><Star size={12} className="fill-current"/>FEATURE</span>}</div><div className="space-y-2 p-3"><button type="button" onClick={()=>setExistingFeature(x.id)} className={`w-full rounded-lg border px-3 py-2 text-xs font-semibold ${x.is_primary?'border-amber-300 bg-amber-50 text-amber-800':'border-zinc-200 hover:bg-zinc-50'}`}><Star size={14} className={`mr-1 inline ${x.is_primary?'fill-current':''}`}/>{x.is_primary?'Feature Image':'Set as Feature'}</button><div className="flex gap-2"><button type="button" className="btn-secondary flex-1 px-2 py-2" disabled={i===0} onClick={()=>moveExistingImage(i,-1)}><ChevronLeft size={15}/></button><button type="button" className="btn-secondary flex-1 px-2 py-2" disabled={i===existingImages.length-1} onClick={()=>moveExistingImage(i,1)}><ChevronRight size={15}/></button><button type="button" className="btn-secondary px-3 py-2 text-red-600" onClick={()=>removeExistingImage(x.id)}><Trash2 size={15}/></button></div></div></article>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-300 p-7 text-center text-sm text-zinc-500">No saved product images yet.</div>}
        </section>}
        <section className={productId&&existingImages.length?'border-t border-zinc-100 pt-7':''}><ImageUploadPicker files={files} onFilesChange={setFiles} primaryIndex={primaryImageIndex} onPrimaryIndexChange={setPrimaryImageIndex} title={existingImages.length?'Add more product images':'Upload product gallery'} description={existingImages.length?'New uploads can become the Feature Image or extend the existing gallery.':'Upload multiple JPG, PNG or WebP images. Choose exactly one Feature Image.'}/></section>
      </div>}
      {step===4&&<div className="space-y-6"><div className="grid gap-5 lg:grid-cols-2"><Field label="Benefits"><Textarea value={form.beauty.benefits} onChange={e=>setForm({...form,beauty:{...form.beauty,benefits:e.target.value}})}/></Field><Field label="Full ingredients"><Textarea value={form.beauty.ingredients_text} onChange={e=>setForm({...form,beauty:{...form.beauty,ingredients_text:e.target.value}})}/></Field><Field label="How to use"><Textarea value={form.beauty.how_to_use} onChange={e=>setForm({...form,beauty:{...form.beauty,how_to_use:e.target.value}})}/></Field><Field label="Precautions"><Textarea value={form.beauty.precautions} onChange={e=>setForm({...form,beauty:{...form.beauty,precautions:e.target.value}})}/></Field><Field label="Country of origin"><Input value={form.beauty.country_of_origin} onChange={e=>setForm({...form,beauty:{...form.beauty,country_of_origin:e.target.value}})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Shelf life"><Input value={form.beauty.shelf_life} onChange={e=>setForm({...form,beauty:{...form.beauty,shelf_life:e.target.value}})}/></Field><Field label="PAO"><Input placeholder="12M" value={form.beauty.pao} onChange={e=>setForm({...form,beauty:{...form.beauty,pao:e.target.value}})}/></Field></div></div>{[['skin_types','Skin Types',skinRows],['hair_types','Hair Types',hairRows],['concerns','Concerns',concernRows],['ingredients','Key Ingredients',ingredientRows]].map(([key,label,rows]:any)=><div key={key}><div className="mb-2 text-sm font-semibold">{label}</div><div className="flex flex-wrap gap-2">{rows.map((x:any)=>{const on=form.beauty[key].includes(x.id);return <button type="button" key={x.id} onClick={()=>toggleBeauty(key,x.id)} className={`rounded-full border px-3 py-1.5 text-xs ${on?'border-pink-400 bg-pink-50 text-pink-800':'border-zinc-200'}`}>{x.name}</button>})}</div></div>)}<div><div className="mb-2 text-sm font-semibold">Claims</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{claimRows.map((x:any)=>{const on=selectedClaims.includes(x.id);return <label key={x.id} className="flex items-center gap-2 rounded-xl border border-zinc-200 p-3 text-sm"><input type="checkbox" checked={on} onChange={()=>setSelectedClaims(a=>on?a.filter(v=>v!==x.id):[...a,x.id])}/>{x.name}</label>})}</div></div></div>}
      {step===5&&<div className="space-y-5"><Field label="Warehouse"><Select value={form.warehouse} onChange={e=>setForm({...form,warehouse:e.target.value})}><option value="">Skip stock update</option>{warehouseRows.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field>{form.product_type==='simple'?<div className="grid gap-4 sm:grid-cols-2"><Field label="Available stock"><Input type="number" min="0" value={form.simple_stock} onChange={e=>setForm({...form,simple_stock:e.target.value})}/></Field><Field label="Low stock threshold"><Input type="number" min="0" value={form.low_stock_threshold} onChange={e=>setForm({...form,low_stock_threshold:e.target.value})}/></Field></div>:<p className="rounded-xl bg-zinc-50 p-4 text-sm text-zinc-600">Variant initial quantities from the Variants step are applied to the selected warehouse.</p>}</div>}
      {step===6&&<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['featured','Featured'],['new_arrival','New arrival'],['bestseller','Bestseller'],['trending','Trending']].map(([key,label])=><div key={key} className="rounded-xl border border-zinc-200 p-4"><Switch checked={!!form[key]} onChange={value=>setForm({...form,[key]:value})} label={label}/></div>)}</div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><b className="text-emerald-900">Ready to publish</b><p className="mt-1 text-sm text-emerald-700">Variable products must have at least one active real variant before the backend allows publication.</p></div></div>}
      <div className="mt-8 flex items-center justify-between border-t border-zinc-100 pt-5"><button type="button" className="btn-secondary" disabled={step===0||busy} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/>Back</button>{step===steps.length-1?<div className="flex gap-2"><button type="button" className="btn-secondary" disabled={busy} onClick={saveAndExit}>Save Draft</button><button type="button" className="btn-brand" disabled={busy} onClick={doPublish}><Check size={16}/>{busy?'Publishing…':'Publish Product'}</button></div>:<button type="button" className="btn-primary" disabled={busy} onClick={next}>{busy?'Saving…':'Save & Continue'}<ArrowRight size={16}/></button>}</div>
    </div>
  </>
}
