import {useEffect,useMemo,useState} from 'react'
import {KeyRound,Save,ShieldCheck,TestTube2,Truck,Wifi} from 'lucide-react'
import {PageHeader} from '../../components/ui/PageHeader'
import {Field,Input,Switch,Textarea} from '../../components/forms/FormField'
import {PageLoading} from '../../components/ui/Loading'
import {ErrorState} from '../../components/ui/ErrorState'
import {useCourierConfigsQuery,useTestCourierConnectionMutation,useUpdateCourierConfigMutation} from '../../services/shippingApi'
import {useAppDispatch} from '../../store/hooks'
import {toast} from '../../features/ui/uiSlice'
import {apiError,rowsOf} from '../../utils/data'
import type {CourierConfig,CourierField} from '../../types'

const valuesFor=(fields:CourierField[],saved:Record<string,string>)=>Object.fromEntries(fields.map(f=>[f.key,saved?.[f.key]??f.default??'']))

function EnvEditor({title,environment,gateway,values,setValues}:{title:string;environment:'sandbox'|'live';gateway:CourierConfig;values:Record<string,string>;setValues:(v:Record<string,string>)=>void}){
 const status=environment==='sandbox'?gateway.sandbox_field_status:gateway.live_field_status
 const configured=environment==='sandbox'?gateway.sandbox_configured:gateway.live_configured
 const disabled=environment==='sandbox'&&!gateway.schema.supports_sandbox
 return <div className={`rounded-2xl border p-4 ${disabled?'border-zinc-200 bg-zinc-50 opacity-60':environment==='sandbox'?'border-amber-200 bg-amber-50/40':'border-zinc-200 bg-white'}`}>
  <div className="mb-4 flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-semibold">{environment==='sandbox'?<TestTube2 size={17}/>:<ShieldCheck size={17}/>} {title}</div><p className="mt-1 text-xs text-zinc-500">{disabled?'This courier has no documented public sandbox.':environment==='sandbox'?'Test bookings only.':'Production credentials for real parcels.'}</p></div><span className={`badge ${configured?'bg-emerald-50 text-emerald-700':'bg-zinc-100 text-zinc-600'}`}>{configured?'Configured':'Not configured'}</span></div>
  {!disabled&&<div className="grid gap-4 md:grid-cols-2">{gateway.schema.fields.map(field=>{const saved=status?.[field.key];const props:any={value:values[field.key]??'',onChange:(e:any)=>setValues({...values,[field.key]:e.target.value}),placeholder:field.secret&&saved?'Saved securely — leave blank to keep':field.placeholder||field.default||'',autoComplete:'new-password'};return <Field key={field.key} label={field.label} required={field.required} hint={field.secret&&saved?'Encrypted value already exists. Enter a new value only to replace it.':undefined}>{field.multiline?<Textarea {...props} rows={5}/>:<Input {...props} type={field.secret?'password':'text'}/>}</Field>})}</div>}
 </div>
}

function CourierCard({gateway}:{gateway:CourierConfig}){
 const dispatch=useAppDispatch(); const [update,{isLoading}]=useUpdateCourierConfigMutation(); const [test,{isLoading:isTesting}]=useTestCourierConnectionMutation()
 const [displayName,setDisplayName]=useState(gateway.display_name),[active,setActive]=useState(gateway.is_active),[sandbox,setSandbox]=useState(gateway.sandbox_mode&&gateway.schema.supports_sandbox),[autoBook,setAutoBook]=useState(gateway.auto_book_enabled),[cancelApi,setCancelApi]=useState(gateway.cancel_api_enabled),[sort,setSort]=useState(String(gateway.sort_order))
 const [sv,setSv]=useState<Record<string,string>>(()=>valuesFor(gateway.schema.fields,gateway.sandbox_values)),[lv,setLv]=useState<Record<string,string>>(()=>valuesFor(gateway.schema.fields,gateway.live_values))
 useEffect(()=>{setDisplayName(gateway.display_name);setActive(gateway.is_active);setSandbox(gateway.sandbox_mode&&gateway.schema.supports_sandbox);setAutoBook(gateway.auto_book_enabled);setCancelApi(gateway.cancel_api_enabled);setSort(String(gateway.sort_order));setSv(valuesFor(gateway.schema.fields,gateway.sandbox_values));setLv(valuesFor(gateway.schema.fields,gateway.live_values))},[gateway])
 const save=async()=>{try{await update({id:gateway.id,body:{display_name:displayName,is_active:active,sandbox_mode:gateway.schema.supports_sandbox?sandbox:false,sort_order:Number(sort||0),auto_book_enabled:autoBook,cancel_api_enabled:gateway.schema.supports_cancel?cancelApi:false,sandbox_config:sv,live_config:lv}}).unwrap();dispatch(toast({type:'success',message:`${displayName} configuration saved.`}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
 const testNow=async()=>{try{await test(gateway.id).unwrap();dispatch(toast({type:'success',message:`${displayName} connection successful.`}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
 return <section className="panel overflow-hidden"><div className="border-b border-zinc-100 p-5 md:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-start gap-3"><span className="rounded-2xl bg-pink-50 p-3 text-pink-800"><Truck size={21}/></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{gateway.schema.label}</h2><span className={`badge ${active?'bg-emerald-50 text-emerald-700':'bg-zinc-100 text-zinc-600'}`}>{active?'Active':'Inactive'}</span>{sandbox&&<span className="badge bg-amber-50 text-amber-700">Sandbox</span>}{autoBook&&<span className="badge bg-blue-50 text-blue-700">Auto booking</span>}</div><p className="mt-1 max-w-2xl text-sm text-zinc-500">{gateway.schema.description}</p></div></div><div className="flex flex-wrap items-center gap-4">{gateway.schema.supports_sandbox&&<Switch checked={sandbox} onChange={setSandbox} label="Sandbox mode"/>}<Switch checked={active} onChange={setActive} label="Active"/><Switch checked={autoBook} onChange={setAutoBook} label="Auto book"/>{gateway.schema.supports_cancel&&<Switch checked={cancelApi} onChange={setCancelApi} label="API cancel"/>}<button className="btn-secondary" disabled={isTesting} onClick={testNow}><Wifi size={16}/>{isTesting?'Testing…':'Test Connection'}</button><button className="btn-brand" disabled={isLoading} onClick={save}><Save size={16}/>{isLoading?'Saving…':'Save'}</button></div></div></div>
 <div className="grid gap-4 p-5 md:p-6 xl:grid-cols-[260px_1fr]"><div className="space-y-4"><Field label="Display name"><Input value={displayName} onChange={e=>setDisplayName(e.target.value)}/></Field><Field label="Priority" hint="Lower number is selected first for auto booking."><Input type="number" min={0} value={sort} onChange={e=>setSort(e.target.value)}/></Field><div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-xs leading-5 text-blue-800"><b>Auto-book trigger:</b> Packed. If Auto book is enabled, a Packed order is submitted automatically using courier priority. Keep it OFF when you want staff to select orders manually from Courier → Courier Orders.</div><div className="rounded-2xl border border-zinc-200 p-4 text-xs leading-5 text-zinc-500"><div><b>Cancellation capability:</b> {gateway.schema.supports_cancel?(cancelApi?'API cancellation opt-in is enabled. Test it in Sandbox before Live.':'Adapter support exists, but API cancellation is OFF until you explicitly opt in after verifying your merchant contract.'):'No verified API cancellation endpoint; dashboard will not falsely mark the provider parcel cancelled.'}</div><div className="mt-2 break-all"><b>Webhook:</b> <code>/api/v1/courier/webhooks/{gateway.provider}/</code></div></div></div><div className="grid gap-4 2xl:grid-cols-2"><EnvEditor title="Sandbox credentials" environment="sandbox" gateway={gateway} values={sv} setValues={setSv}/><EnvEditor title="Live credentials" environment="live" gateway={gateway} values={lv} setValues={setLv}/></div></div></section>
}

export default function CourierIntegrationsPage(){const q=useCourierConfigsQuery();const rows=useMemo(()=>rowsOf<CourierConfig>(q.data),[q.data]);if(q.isLoading)return <PageLoading/>;if(q.isError)return <ErrorState onRetry={()=>q.refetch()}/>;return <><PageHeader title="Courier Integrations" description="Configure Pathao, Steadfast, RedX and CarryBee credentials, sandbox/live environments, availability and automatic booking."/><div className="mb-5 flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800"><KeyRound size={18} className="mt-0.5 shrink-0"/><div>Set a stable <code>COURIER_CONFIG_ENCRYPTION_KEY</code> in production. Secret credentials are encrypted and never returned to the browser after saving.</div></div><div className="space-y-5">{rows.map(x=><CourierCard key={x.id} gateway={x}/>)}</div></>}
