import {useMemo,useState} from 'react'
import {BarChart3,Download,FileSpreadsheet,RefreshCw} from 'lucide-react'
import {PageHeader} from '../../components/ui/PageHeader'
import {TrendChart} from '../../components/charts/TrendChart'
import {StatCard} from '../../components/ui/StatCard'
import {StatusBadge} from '../../components/ui/StatusBadge'
import {LoadingRows} from '../../components/ui/Loading'
import {ErrorState} from '../../components/ui/ErrorState'
import {useReportQuery,useExportsQuery,useCreateExportMutation} from '../../services/reportApi'
import {apiError,rowsOf} from '../../utils/data'
import {date,money,titleCase} from '../../utils/format'
import {useAppDispatch,useAppSelector} from '../../store/hooks'
import {toast} from '../../features/ui/uiSlice'

const reports=[['sales','Sales'],['profit','Profit'],['orders','Orders'],['product-performance','Product'],['category-performance','Category'],['brand-performance','Brand'],['inventory','Inventory'],['stock-aging','Stock Aging'],['dead-stock','Dead Stock'],['low-performing-products','Low Performing'],['best-sellers','Best Sellers'],['customers','Customers'],['customer-lifetime-value','Customer Lifetime Value'],['payments','Payments'],['returns','Returns'],['refunds','Refunds'],['discounts','Discounts'],['coupon-performance','Coupon Performance'],['sales-geography','Sales Geography'],['funnel','Funnel']] as const
const preset=(key:string)=>{const now=new Date(),end=new Date(now),start=new Date(now);if(key==='today')start.setHours(0,0,0,0);else if(key==='yesterday'){start.setDate(start.getDate()-1);start.setHours(0,0,0,0);end.setDate(end.getDate()-1);end.setHours(23,59,59,999)}else if(key==='7')start.setDate(start.getDate()-7);else if(key==='30')start.setDate(start.getDate()-30);else if(key==='month'){start.setDate(1);start.setHours(0,0,0,0)}else if(key==='last_month'){start.setMonth(start.getMonth()-1,1);start.setHours(0,0,0,0);end.setDate(0);end.setHours(23,59,59,999)}else if(key==='year'){start.setMonth(0,1);start.setHours(0,0,0,0)}return {start:start.toISOString(),end:end.toISOString()}}
const flat=(value:any)=>value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,typeof v==='object'&&v!==null?JSON.stringify(v):v])):value
const isMoneyKey=(key:string)=>/revenue|sales|amount|value|discount|cogs|profit|price|lifetime|shipping|tax/i.test(key)
const excelDownload=(rows:any[],name:string)=>{if(!rows.length)return false;const keys=Array.from(new Set(rows.flatMap(row=>Object.keys(row))));const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');const html=`<html><head><meta charset="UTF-8"></head><body><table><thead><tr>${keys.map(k=>`<th>${esc(titleCase(k.replaceAll('__',' ')))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${name}-${new Date().toISOString().slice(0,10)}.xls`;a.click();URL.revokeObjectURL(url);return true}

export default function ReportsPage(){
  const dispatch=useAppDispatch(),role=useAppSelector(s=>s.auth.user?.role); const [type,setType]=useState('sales'),[period,setPeriod]=useState('30'),[custom,setCustom]=useState({start:'',end:''}); const range=period==='custom'?{start:custom.start?new Date(`${custom.start}T00:00:00`).toISOString():undefined,end:custom.end?new Date(`${custom.end}T23:59:59`).toISOString():undefined}:preset(period)
  const q=useReportQuery({type,...range}); const exports=useExportsQuery(undefined,{pollingInterval:5000}); const [createExport,{isLoading:exporting}]=useCreateExportMutation(); const raw:any=q.data; const rows=Array.isArray(raw)?raw:raw&&typeof raw==='object'?[flat(raw)]:[]
  const chart=useMemo(()=>{if(type==='sales')return rows.map((x:any)=>({name:String(x.day||'').slice(5),value:Number(x.sales||0)}));if(type==='orders')return rows.map((x:any)=>({name:titleCase(x.order_status||''),value:Number(x.count||0)}));if(type==='product-performance'||type==='best-sellers')return rows.slice(0,12).map((x:any)=>({name:x.product_name_snapshot||`#${x.product_id}`,value:Number(x.revenue||0)}));if(type==='category-performance')return rows.slice(0,12).map((x:any)=>({name:x.product__category__name||'Unknown',value:Number(x.revenue||0)}));if(type==='brand-performance')return rows.slice(0,12).map((x:any)=>({name:x.product__brand__name||'Unknown',value:Number(x.revenue||0)}));if(type==='sales-geography')return rows.slice(0,12).map((x:any)=>({name:x.district||'Unknown',value:Number(x.sales||0)}));if(type==='funnel'&&raw)return Object.entries(raw).map(([k,v])=>({name:titleCase(k),value:Number(v||0)}));return []},[type,raw,rows])
  const queueExport=async()=>{try{await createExport({report:type,params:range}).unwrap();dispatch(toast({type:'success',message:'Excel export queued. The download link will appear below.'}));exports.refetch()}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
  const downloadNow=()=>{if(!excelDownload(rows,type))dispatch(toast({type:'error',message:'No report rows to export.'}))}
  const keys=rows.length?Object.keys(rows[0]).filter(k=>k!=='id').slice(0,16):[]
  return <>
    <PageHeader title="Reports" description="Interactive database-level reports with date filters and Excel export." actions={<><button className="btn-secondary" onClick={downloadNow}><Download size={16}/>Excel now</button><button className="btn-brand" disabled={exporting} onClick={queueExport}><FileSpreadsheet size={16}/>{exporting?'Queuing…':'Queue XLSX'}</button></>}/>
    <div className="panel mb-5 grid gap-3 p-4 lg:grid-cols-[1.3fr_1fr_auto]"><select className="input" value={type} onChange={e=>setType(e.target.value)}>{reports.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select className="input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="7">7 Days</option><option value="30">30 Days</option><option value="month">This Month</option><option value="last_month">Last Month</option><option value="year">This Year</option><option value="custom">Custom</option></select><button className="btn-secondary" onClick={()=>q.refetch()}><RefreshCw size={15}/>Refresh</button>{period==='custom'&&<div className="grid gap-2 sm:grid-cols-2 lg:col-span-3"><input className="input" type="date" value={custom.start} onChange={e=>setCustom({...custom,start:e.target.value})}/><input className="input" type="date" value={custom.end} onChange={e=>setCustom({...custom,end:e.target.value})}/></div>}</div>
    {q.isLoading?<LoadingRows rows={8}/>:q.isError?<ErrorState onRetry={q.refetch}/>:type==='profit'&&raw?<div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><StatCard label="Product Revenue" value={money(raw.product_revenue)}/><StatCard label="Discounts" value={money(raw.discounts)}/><StatCard label="Net Revenue" value={money(raw.net_product_revenue)}/><StatCard label="COGS" value={money(raw.cogs)}/><StatCard label="Gross Profit" value={money(raw.gross_profit)} tone={Number(raw.gross_profit)>=0?'success':'danger'}/><StatCard label="Margin" value={`${Number(raw.margin_percentage||0).toFixed(1)}%`}/></div>:type==='discounts'&&raw?<div className="grid gap-3 sm:grid-cols-2"><StatCard label="Total Discount" value={money(raw.total_discount)}/><StatCard label="Orders With Discount" value={raw.orders_with_discount||0}/></div>:<>
      {chart.length>0&&<div className="panel mb-5 p-5"><div className="mb-3"><h2 className="font-semibold">{reports.find(x=>x[0]===type)?.[1]} overview</h2><p className="text-xs text-zinc-400">Selected date range</p></div><TrendChart data={chart} kind={['orders','funnel','category-performance','brand-performance','sales-geography'].includes(type)?'bar':'area'}/></div>}
      {rows.length?<div className="table-wrap overflow-x-auto"><table className="table"><thead><tr>{keys.map(k=><th key={k}>{titleCase(k.replaceAll('__',' '))}</th>)}</tr></thead><tbody>{rows.slice(0,500).map((row:any,index:number)=><tr key={row.id||index}>{keys.map(k=><td key={k}>{row[k]===null||row[k]===undefined?'—':isMoneyKey(k)?money(row[k]):String(row[k])}</td>)}</tr>)}</tbody></table></div>:<div className="panel p-10 text-center"><BarChart3 className="mx-auto text-zinc-300"/><h3 className="mt-3 font-semibold">No report data</h3><p className="mt-1 text-sm text-zinc-500">There are no records for the selected date range.</p></div>}
    </>}
    <section className="panel mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-zinc-100 p-5"><div><h2 className="font-semibold">Excel export jobs</h2><p className="text-xs text-zinc-400">Large exports are generated by Celery as XLSX files.</p></div><span className="text-xs text-zinc-400">Role: {titleCase(role||'')}</span></div><div className="divide-y divide-zinc-100">{rowsOf<any>(exports.data).slice(0,10).map(job=><div key={job.id} className="flex items-center gap-3 px-5 py-3"><div className="flex-1"><b className="text-sm">{titleCase(job.report)}</b><div className="text-xs text-zinc-400">{date(job.created_at,true)}{job.error?` · ${job.error}`:''}</div></div><StatusBadge value={job.status}/>{job.file&&<a className="btn-secondary py-2" href={job.file} target="_blank" rel="noreferrer">Download XLSX</a>}</div>)}</div></section>
  </>
}
