import {useState} from 'react'
import {History,RefreshCw,Search,Truck,XCircle,RotateCcw} from 'lucide-react'
import {PageHeader} from '../../components/ui/PageHeader'
import {DataTable,type Column} from '../../components/ui/DataTable'
import {StatusBadge} from '../../components/ui/StatusBadge'
import {Modal} from '../../components/ui/Modal'
import {Pagination} from '../../components/ui/Pagination'
import {LoadingRows} from '../../components/ui/Loading'
import {ErrorState} from '../../components/ui/ErrorState'
import {Field,Input,Select,Textarea} from '../../components/forms/FormField'
import {useAvailableCouriersQuery,useBookShipmentMutation,useCancelShipmentMutation,useRequestShipmentReturnMutation,useShipmentsQuery,useTrackShipmentMutation,useLazyShipmentHistoryQuery} from '../../services/shippingApi'
import {useOrdersQuery} from '../../services/orderApi'
import {rowsOf,countOf,apiError} from '../../utils/data'
import {date,titleCase} from '../../utils/format'
import {useAppDispatch} from '../../store/hooks'
import {toast} from '../../features/ui/uiSlice'
import {useDebouncedValue} from '../../hooks/useDebouncedValue'

export default function ShipmentsPage(){
 const dispatch=useAppDispatch(),[page,setPage]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[courier,setCourier]=useState(''),[open,setOpen]=useState(false),[reasonOpen,setReasonOpen]=useState<any>(null),[historyOpen,setHistoryOpen]=useState<any>(null),[reason,setReason]=useState(''),[form,setForm]=useState({order:'',provider:'',delivery_area_id:'',delivery_area:'',city_id:'',zone_id:'',area_id:'',weight:''})
 const debounced=useDebouncedValue(search,300),q=useShipmentsQuery({page,page_size:50,search:debounced||undefined,status:status||undefined,courier:courier||undefined}),orders=useOrdersQuery({page_size:200,order_status:'packed'}),couriers=useAvailableCouriersQuery()
 const [book,{isLoading:booking}]=useBookShipmentMutation(),[track]=useTrackShipmentMutation(),[cancel]=useCancelShipmentMutation(),[requestReturn]=useRequestShipmentReturnMutation(),[loadHistory,{data:historyData,isFetching:historyLoading}]=useLazyShipmentHistoryQuery()
 const opts=rowsOf<any>(couriers.data)
 const actTrack=async(id:number)=>{try{await track(id).unwrap();dispatch(toast({type:'success',message:'Tracking synced.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
 const cols:Column<any>[]=[
  {key:'tracking',header:'Tracking',render:r=><div><b>{r.tracking_code||`Shipment #${r.id}`}</b><div className="text-xs text-zinc-400">{r.external_id||'—'}</div></div>},
  {key:'order',header:'Order',render:r=><div><b>{r.order_number||`#${r.order}`}</b><div className="text-xs text-zinc-400">{r.customer_name||''}</div></div>},
  {key:'courier',header:'Courier',render:r=><div>{r.courier_display||r.courier}<div className="text-xs text-zinc-400">{r.environment||'—'} · {r.booking_source||'manual'}</div></div>},
  {key:'status',header:'Status',render:r=><div><StatusBadge value={r.status}/><div className="mt-1 text-xs text-zinc-400">{r.provider_status||'—'}</div></div>},
  {key:'date',header:'Last Sync',render:r=>r.last_synced_at?date(r.last_synced_at,true):'—'},
  {key:'action',header:'Actions',render:r=><div className="flex flex-wrap gap-2"><button className="btn-secondary py-2" onClick={()=>actTrack(r.id)}><RefreshCw size={14}/>Track</button><button className="btn-secondary py-2" onClick={()=>{setHistoryOpen(r);void loadHistory(r.id)}}><History size={14}/>History</button>{r.can_cancel&&<button className="btn-secondary py-2 text-red-600" onClick={()=>{setReason('');setReasonOpen({shipment:r,action:'cancel'})}}><XCircle size={14}/>Cancel</button>}{r.courier==='steadfast'&&!['delivered','returned','cancelled'].includes(r.status)&&<button className="btn-secondary py-2" onClick={()=>{setReason('');setReasonOpen({shipment:r,action:'return'})}}><RotateCcw size={14}/>Return Request</button>}</div>},
 ]
 const submitBook=async()=>{try{const options:any={};if(form.delivery_area_id)options.delivery_area_id=Number(form.delivery_area_id);if(form.delivery_area)options.delivery_area=form.delivery_area;if(form.provider==='carrybee'){if(form.city_id)options.city_id=Number(form.city_id);if(form.zone_id)options.zone_id=Number(form.zone_id);if(form.area_id)options.area_id=Number(form.area_id)};if(form.weight){if(form.provider==='redx'||form.provider==='carrybee')options.weight_grams=Number(form.weight);else options.weight_kg=Number(form.weight)};await book({order:Number(form.order),provider:form.provider,options}).unwrap();setOpen(false);dispatch(toast({type:'success',message:'Shipment booked with courier.'}))}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}
 return <><PageHeader title="Courier Shipments" description="Book parcels, sync live courier status, cancel supported parcels and review automated shipments." actions={<button className="btn-brand" onClick={()=>{setForm({order:'',provider:opts[0]?.provider||'',delivery_area_id:'',delivery_area:'',city_id:'',zone_id:'',area_id:'',weight:''});setOpen(true)}}><Truck size={16}/>Book Shipment</button>}/>
 <div className="mb-4 grid gap-2 md:grid-cols-3"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input className="input pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Tracking, order, customer, phone…"/></label><select className="input" value={courier} onChange={e=>{setCourier(e.target.value);setPage(1)}}><option value="">All couriers</option>{opts.map(x=><option key={x.provider} value={x.provider}>{x.display_name}</option>)}</select><select className="input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['pending','booked','picked','in_transit','out_for_delivery','delivered','returned','failed','cancelled'].map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select></div>
 {q.isLoading?<LoadingRows/>:q.isError?<ErrorState onRetry={()=>q.refetch()}/>:<><DataTable rows={rowsOf<any>(q.data)} columns={cols} getKey={r=>r.id}/><Pagination count={countOf(q.data)} page={page} onPage={setPage}/></>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Book Courier Shipment"><div className="space-y-4"><Field label="Order"><Select value={form.order} onChange={e=>setForm({...form,order:e.target.value})}><option value="">Select order</option>{rowsOf<any>(orders.data).map(o=><option key={o.id} value={o.id}>{o.order_number} · {o.customer_name}</option>)}</Select></Field><Field label="Courier"><Select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="">Select active courier</option>{opts.map(x=><option key={x.provider} value={x.provider}>{x.display_name} {x.environment==='sandbox'?'(Sandbox)':''}</option>)}</Select></Field>{form.provider==='redx'&&<><Field label="RedX Delivery Area ID" hint="Optional. Backend tries to match district/thana automatically; enter ID if matching fails."><Input type="number" value={form.delivery_area_id} onChange={e=>setForm({...form,delivery_area_id:e.target.value})}/></Field><Field label="RedX Delivery Area Name"><Input value={form.delivery_area} onChange={e=>setForm({...form,delivery_area:e.target.value})}/></Field></>}{form.provider==='carrybee'&&<div className="grid gap-3 rounded-xl border border-zinc-200 p-3 md:grid-cols-3"><div className="md:col-span-3 text-xs text-zinc-500">CarryBee location IDs are optional. The backend first resolves city/zone from the order address; use these overrides only when automatic matching fails.</div><Field label="CarryBee City ID"><Input type="number" value={form.city_id} onChange={e=>setForm({...form,city_id:e.target.value})}/></Field><Field label="CarryBee Zone ID"><Input type="number" value={form.zone_id} onChange={e=>setForm({...form,zone_id:e.target.value})}/></Field><Field label="CarryBee Area ID" hint="Optional"><Input type="number" value={form.area_id} onChange={e=>setForm({...form,area_id:e.target.value})}/></Field></div>}<Field label={form.provider==='redx'||form.provider==='carrybee'?'Parcel Weight (grams)':'Parcel Weight (kg)'}><Input type="number" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} placeholder={form.provider==='redx'||form.provider==='carrybee'?'500':'0.5'}/></Field><button className="btn-brand w-full" disabled={booking||!form.order||!form.provider} onClick={submitBook}><Truck size={16}/>{booking?'Booking…':'Book With Courier'}</button></div></Modal>
 <Modal open={!!historyOpen} onClose={()=>setHistoryOpen(null)} title={`Courier Event History${historyOpen?.tracking_code?` · ${historyOpen.tracking_code}`:''}`}><div className="max-h-[65vh] space-y-3 overflow-y-auto">{historyLoading?<p className="text-sm text-zinc-500">Loading history…</p>:(historyData||[]).length?(historyData||[]).map((event:any)=><div key={event.id} className="rounded-xl border border-zinc-200 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm">{titleCase(event.action)}</b><span className={`badge ${event.success?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{event.success?'Success':'Failed'}</span></div><p className="mt-1 text-xs text-zinc-400">{date(event.created_at,true)}{event.requested_by_name?` · ${event.requested_by_name}`:''}</p>{event.error?<p className="mt-2 text-xs text-red-600">{event.error}</p>:null}</div>):<p className="text-sm text-zinc-500">No courier events recorded yet.</p>}</div></Modal>
 <Modal open={!!reasonOpen} onClose={()=>setReasonOpen(null)} title={reasonOpen?.action==='return'?'Request Courier Return':'Cancel Courier Shipment'}><div className="space-y-4"><Field label="Reason"><Textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><button className="btn-brand w-full" onClick={async()=>{try{if(reasonOpen?.action==='return')await requestReturn({id:reasonOpen.shipment.id,reason}).unwrap();else await cancel({id:reasonOpen.shipment.id,reason}).unwrap();dispatch(toast({type:'success',message:reasonOpen?.action==='return'?'Return request submitted.':'Cancellation submitted.'}));setReasonOpen(null)}catch(e){dispatch(toast({type:'error',message:apiError(e)}))}}}>{reasonOpen?.action==='return'?'Submit Return Request':'Submit Cancellation'}</button></div></Modal>
 </>}
