import {useState} from 'react'
import {Search} from 'lucide-react'
import {PageHeader} from '../../components/ui/PageHeader'
import {DataTable,type Column} from '../../components/ui/DataTable'
import {LoadingRows} from '../../components/ui/Loading'
import {ErrorState} from '../../components/ui/ErrorState'
import {Pagination} from '../../components/ui/Pagination'
import {useMovementsQuery,useWarehousesQuery} from '../../services/inventoryApi'
import {rowsOf,countOf} from '../../utils/data'
import {date,titleCase} from '../../utils/format'
import {StatusBadge} from '../../components/ui/StatusBadge'
import {useDebouncedValue} from '../../hooks/useDebouncedValue'

export default function MovementsPage(){
 const [page,setPage]=useState(1),[type,setType]=useState(''),[warehouse,setWarehouse]=useState(''),[search,setSearch]=useState('')
 const debounced=useDebouncedValue(search,300)
 const q=useMovementsQuery({page,page_size:50,search:debounced||undefined,movement_type:type||undefined,warehouse:warehouse||undefined}),ws=useWarehousesQuery({page_size:500})
 const cols:Column<any>[]=[{key:'date',header:'Date',render:r=>date(r.created_at,true)},{key:'item',header:'Stock Item',render:r=>`#${r.stock_item}`},{key:'warehouse',header:'Warehouse',render:r=>rowsOf<any>(ws.data).find(w=>w.id===r.warehouse)?.name||r.warehouse},{key:'type',header:'Movement',render:r=><StatusBadge value={r.movement_type}/>},{key:'qty',header:'Quantity',render:r=><b className={Number(r.quantity)>=0?'text-emerald-700':'text-red-600'}>{Number(r.quantity)>0?'+':''}{r.quantity}</b>},{key:'before',header:'Before → After',render:r=>`${r.before_quantity} → ${r.after_quantity}`},{key:'ref',header:'Reference',render:r=><span className="text-xs">{titleCase(r.reference_type)} #{r.reference_id}</span>},{key:'note',header:'Note',render:r=><span className="line-clamp-2 max-w-xs">{r.note||'—'}</span>}]
 return <><PageHeader title="Stock Movements" description="Searchable immutable history generated by purchases, sales, returns, adjustments and transfers."/><div className="mb-4 grid gap-2 md:grid-cols-3"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400"/><input className="input pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Product, SKU, note, reference…"/></label><select className="input" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All movement types</option>{['purchase','sale','return','cancellation','adjustment','damage','transfer','restock'].map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select><select className="input" value={warehouse} onChange={e=>{setWarehouse(e.target.value);setPage(1)}}><option value="">All warehouses</option>{rowsOf<any>(ws.data).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>{q.isLoading?<LoadingRows/>:q.isError?<ErrorState onRetry={()=>q.refetch()}/>:<><DataTable rows={rowsOf<any>(q.data)} columns={cols} getKey={r=>r.id}/><Pagination count={countOf(q.data)} page={page} onPage={setPage}/></>}</>}
